export type FETCH = 'FETCH';
export const FETCH: FETCH = 'FETCH';

export type SET = 'SET';
export const SET: SET = 'SET';

export type CLICK = 'CLICK';
export const CLICK: CLICK = 'CLICK';

export type SET_SESSION = 'SET_SESSION';
export const SET_SESSION: SET_SESSION = 'SET_SESSION';

export type APP_MOUNTED = 'APP_MOUNTED';
export const APP_MOUNTED: APP_MOUNTED = 'APP_MOUNTED';

export type SET_YOUR_CLICKS= 'SET_YOUR_CLICKS';
export const SET_YOUR_CLICKS: SET_YOUR_CLICKS = 'SET_YOUR_CLICKS';

export type SET_TEAM_CLICKS= 'SET_TEAM_CLICKS';
export const SET_TEAM_CLICKS: SET_TEAM_CLICKS = 'SET_TEAM_CLICKS';

export type SET_TEAM_NAME= 'SET_TEAM_NAME';
export const SET_TEAM_NAME: SET_TEAM_NAME = 'SET_TEAM_NAME';

export type FETCH_TEAM_CLICKS = 'FETCH_TEAM_CLICKS';
export const FETCH_TEAM_CLICKS: FETCH_TEAM_CLICKS = 'FETCH_TEAM_CLICKS';
